services:

  backend:
    build: ./backend
    container_name: fintech_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fintech_db
      SPRING_DATASOURCE_USERNAME: midrel
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on:
      db:
       condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: fintech_db
    environment:
      POSTGRES_DB: fintech_db
      POSTGRES_USER: midrel
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U midrel -d fintech_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  pg_data:    