services:

  backend:
    build: .
    container_name: fintech_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fintech_db
      SPRING_DATASOURCE_USERNAME: midrel
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      db:
       condition: service_healthy
    restart: unless-stopped
    networks:
      - fintechapp-net

  db:
    image: postgres:16-alpine
    container_name: fintech_db
    environment:
      POSTGRES_DB: fintech_db
      POSTGRES_USER: midrel
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./fintech_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U midrel -d fintech_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: fintech_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - fintechapp-net

networks:
  fintechapp-net:
    driver: bridge

volumes:
  pg_data:    